// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZw9xICI7tBCtooI1mYhr7L_WEwSnOrIU',
    appId: '1:603827073867:web:a7a78f6746688f6c0deece',
    messagingSenderId: '603827073867',
    projectId: 'stock-screener-f9494',
    authDomain: 'stock-screener-f9494.firebaseapp.com',
    storageBucket: 'stock-screener-f9494.firebasestorage.app',
    measurementId: 'G-EWLE60MGBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWEVizSdUwl9zzM3kEP0bF013ACXn8M-E',
    appId: '1:603827073867:android:3d9547a15fab95760deece',
    messagingSenderId: '603827073867',
    projectId: 'stock-screener-f9494',
    storageBucket: 'stock-screener-f9494.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOKF2j69pAZma6-TIQAdn8qY_8-EWBRdY',
    appId: '1:603827073867:ios:3fce857dbb681d000deece',
    messagingSenderId: '603827073867',
    projectId: 'stock-screener-f9494',
    storageBucket: 'stock-screener-f9494.firebasestorage.app',
    iosBundleId: 'com.example.stockScreener',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOKF2j69pAZma6-TIQAdn8qY_8-EWBRdY',
    appId: '1:603827073867:ios:3fce857dbb681d000deece',
    messagingSenderId: '603827073867',
    projectId: 'stock-screener-f9494',
    storageBucket: 'stock-screener-f9494.firebasestorage.app',
    iosBundleId: 'com.example.stockScreener',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZw9xICI7tBCtooI1mYhr7L_WEwSnOrIU',
    appId: '1:603827073867:web:fe3e81d7d5318af20deece',
    messagingSenderId: '603827073867',
    projectId: 'stock-screener-f9494',
    authDomain: 'stock-screener-f9494.firebaseapp.com',
    storageBucket: 'stock-screener-f9494.firebasestorage.app',
    measurementId: 'G-D3RZYKSM32',
  );
}
